FROM maven:3.8-openjdk-17 AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests \
    && ls -l /app/target

FROM eclipse-temurin:17-jre 
WORKDIR /app
COPY --from=builder /app/target/commerce.service-0.0.1-SNAPSHOT.jar /app/commerce.service.jar

EXPOSE 8080

CMD ["java", "-jar", "commerce.service.jar"]